source "http://rubygems.org"

gem 'json'
gem 'i18n'
gem 'active_support'
gem 'uuid'
gem 'eventmachine', :git => "git://github.com/eventmachine/eventmachine.git"
gem 'em-synchrony', :git => "git://github.com/igrigorik/em-synchrony.git"